---

- name: install and configure Apache Webserver
  hosts: everything
  vars:
    HTTP_PORT: 83
    VHOST_NAME: vhost_on_83

  tasks:
  - name: install Apache
    yum: name=httpd state=latest

  - name: start Apache service
    service: name=httpd state=started enabled=yes

  - name: create Apache Virtual-Host configuration file
    template: src=virtual-host.j2 dest=/etc/httpd/conf.d/{{ VHOST_NAME }}.conf
    notify: restart httpd

  - name: Allow port on firewall
    firewalld:
      port: "{{ HTTP_PORT }}/tcp"
      permanent: yes
      state: enabled
    notify:
      - restart firewalld

  - name: Create Virtual-Host directory
    file:
      path: /var/www/{{ VHOST_NAME }}
      state: directory
      mode: 0755

  - name: Create index.html for Virtual-Host
    copy:
      dest: "/var/www/{{ VHOST_NAME }}/index.html"
      content: This response is from port {{ HTTP_PORT }}

  handlers:
  - name: restart httpd
    service: name=httpd state=restarted

  - name: restart firewalld
    service: name=firewalld state=restarted
